# -*- coding: utf-8 -*-
"""openrouter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEv2B2NQe-CGwPVM-VzA4A6rmiqoVYQL
"""
#Start-CELL1---------------------------------------------------------------------------
# ขั้นตอนที่ 1: ติดตั้ง library ที่จำเป็น
!pip install openai

# ขั้นตอนที่ 2: Import library และตั้งค่า
import os
from openai import OpenAI

# ตั้งค่า API key ของคุณ
# แนะนำให้ใช้ Secret Management ของ Colab เพื่อความปลอดภัย
# โดยไปที่ไอคอนรูปกุญแจ (Secrets) ด้านซ้าย -> เพิ่ม Secret ใหม่
# ชื่อ: OPENROUTER_API_KEY, ค่า: sk-or-v1-.... (API Key ของคุณ)
from google.colab import userdata
OPENROUTER_API_KEY = userdata.get('openrouter') # Corrected secret name

# ขั้นตอนที่ 3: สร้าง client เพื่อเชื่อมต่อกับ OpenRouter
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=OPENROUTER_API_KEY,
)

# ขั้นตอนที่ 4: เรียกใช้งานโมเดล
# คุณสามารถเปลี่ยนชื่อโมเดลได้ตามต้องการ ดูรายชื่อโมเดลทั้งหมดได้ที่ https://openrouter.ai/models
# ตัวอย่างนี้ใช้โมเดลฟรี "Haiku" ของ Anthropic
completion = client.chat.completions.create(
  model="qwen/qwen3-coder:free", # <-- เปลี่ยนชื่อโมเดลที่นี่
  messages=[
    {
      "role": "user",
      "content": "เหล้ากับเบียร์แตกต่างกันอย่างไร",
    },
  ],
)

# แสดงผลลัพธ์
print(completion.choices[0].message.content)

#END-CELL1---------------------------------------------------------------------------

#Start-CELL2---------------------------------------------------------------------------
# ขั้นตอนที่ 4: เรียกใช้งานโมเดล
# คุณสามารถเปลี่ยนชื่อโมเดลได้ตามต้องการ ดูรายชื่อโมเดลทั้งหมดได้ที่ https://openrouter.ai/models
# ตัวอย่างนี้ใช้โมเดลฟรี "Haiku" ของ Anthropic
completion = client.chat.completions.create(
  model="qwen/qwen3-coder:free", # <-- เปลี่ยนชื่อโมเดลที่นี่
  messages=[
    {
      "role": "user",
      "content": "เหล้ากับเบียร์แตกต่างกันอย่างไร",
    },
  ],
)

# แสดงผลลัพธ์
print(completion.choices[0].message.content)

#END-CELL2---------------------------------------------------------------------------

#Start-CELL3---------------------------------------------------------------------------
# ขั้นตอนที่ 4: เรียกใช้งานโมเดล
# คุณสามารถเปลี่ยนชื่อโมเดลได้ตามต้องการ ดูรายชื่อโมเดลทั้งหมดได้ที่ https://openrouter.ai/models
# ตัวอย่างนี้ใช้โมเดลฟรี "Haiku" ของ Anthropic
completion = client.chat.completions.create(
  model="meta-llama/llama-3.2-3b-instruct:free", # <-- เปลี่ยนชื่อโมเดลที่นี่
  messages=[
    {
      "role": "user",
      "content": "เหล้ากับเบียร์แตกต่างกันอย่างไร",
    },
  ],
)

# แสดงผลลัพธ์
print(completion.choices[0].message.content)

#END-CELL3---------------------------------------------------------------------------